/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as ProductsIndexRouteImport } from './routes/products/index'
import { Route as JobsIndexRouteImport } from './routes/jobs/index'
import { Route as GoogleFeedIndexRouteImport } from './routes/google-feed/index'
import { Route as BulkOperationsIndexRouteImport } from './routes/bulk-operations/index'
import { Route as SettingsPromptsRouteImport } from './routes/settings/prompts'
import { Route as ProductsProductIdRouteImport } from './routes/products/$productId'
import { Route as JobsJobIdRouteImport } from './routes/jobs/$jobId'
import { Route as GoogleFeedRulesIndexRouteImport } from './routes/google-feed/rules/index'
import { Route as GoogleFeedPreviewIndexRouteImport } from './routes/google-feed/preview/index'
import { Route as GoogleFeedHistoryIndexRouteImport } from './routes/google-feed/history/index'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsIndexRoute = JobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => rootRouteImport,
} as any)
const GoogleFeedIndexRoute = GoogleFeedIndexRouteImport.update({
  id: '/google-feed/',
  path: '/google-feed/',
  getParentRoute: () => rootRouteImport,
} as any)
const BulkOperationsIndexRoute = BulkOperationsIndexRouteImport.update({
  id: '/bulk-operations/',
  path: '/bulk-operations/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsPromptsRoute = SettingsPromptsRouteImport.update({
  id: '/settings/prompts',
  path: '/settings/prompts',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsProductIdRoute = ProductsProductIdRouteImport.update({
  id: '/products/$productId',
  path: '/products/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsJobIdRoute = JobsJobIdRouteImport.update({
  id: '/jobs/$jobId',
  path: '/jobs/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const GoogleFeedRulesIndexRoute = GoogleFeedRulesIndexRouteImport.update({
  id: '/google-feed/rules/',
  path: '/google-feed/rules/',
  getParentRoute: () => rootRouteImport,
} as any)
const GoogleFeedPreviewIndexRoute = GoogleFeedPreviewIndexRouteImport.update({
  id: '/google-feed/preview/',
  path: '/google-feed/preview/',
  getParentRoute: () => rootRouteImport,
} as any)
const GoogleFeedHistoryIndexRoute = GoogleFeedHistoryIndexRouteImport.update({
  id: '/google-feed/history/',
  path: '/google-feed/history/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/settings/prompts': typeof SettingsPromptsRoute
  '/bulk-operations/': typeof BulkOperationsIndexRoute
  '/google-feed/': typeof GoogleFeedIndexRoute
  '/jobs/': typeof JobsIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/google-feed/history/': typeof GoogleFeedHistoryIndexRoute
  '/google-feed/preview/': typeof GoogleFeedPreviewIndexRoute
  '/google-feed/rules/': typeof GoogleFeedRulesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/settings/prompts': typeof SettingsPromptsRoute
  '/bulk-operations': typeof BulkOperationsIndexRoute
  '/google-feed': typeof GoogleFeedIndexRoute
  '/jobs': typeof JobsIndexRoute
  '/products': typeof ProductsIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/google-feed/history': typeof GoogleFeedHistoryIndexRoute
  '/google-feed/preview': typeof GoogleFeedPreviewIndexRoute
  '/google-feed/rules': typeof GoogleFeedRulesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/settings/prompts': typeof SettingsPromptsRoute
  '/bulk-operations/': typeof BulkOperationsIndexRoute
  '/google-feed/': typeof GoogleFeedIndexRoute
  '/jobs/': typeof JobsIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/google-feed/history/': typeof GoogleFeedHistoryIndexRoute
  '/google-feed/preview/': typeof GoogleFeedPreviewIndexRoute
  '/google-feed/rules/': typeof GoogleFeedRulesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/jobs/$jobId'
    | '/products/$productId'
    | '/settings/prompts'
    | '/bulk-operations/'
    | '/google-feed/'
    | '/jobs/'
    | '/products/'
    | '/settings/'
    | '/google-feed/history/'
    | '/google-feed/preview/'
    | '/google-feed/rules/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/jobs/$jobId'
    | '/products/$productId'
    | '/settings/prompts'
    | '/bulk-operations'
    | '/google-feed'
    | '/jobs'
    | '/products'
    | '/settings'
    | '/google-feed/history'
    | '/google-feed/preview'
    | '/google-feed/rules'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/jobs/$jobId'
    | '/products/$productId'
    | '/settings/prompts'
    | '/bulk-operations/'
    | '/google-feed/'
    | '/jobs/'
    | '/products/'
    | '/settings/'
    | '/google-feed/history/'
    | '/google-feed/preview/'
    | '/google-feed/rules/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  JobsJobIdRoute: typeof JobsJobIdRoute
  ProductsProductIdRoute: typeof ProductsProductIdRoute
  SettingsPromptsRoute: typeof SettingsPromptsRoute
  BulkOperationsIndexRoute: typeof BulkOperationsIndexRoute
  GoogleFeedIndexRoute: typeof GoogleFeedIndexRoute
  JobsIndexRoute: typeof JobsIndexRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  GoogleFeedHistoryIndexRoute: typeof GoogleFeedHistoryIndexRoute
  GoogleFeedPreviewIndexRoute: typeof GoogleFeedPreviewIndexRoute
  GoogleFeedRulesIndexRoute: typeof GoogleFeedRulesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/': {
      id: '/jobs/'
      path: '/jobs'
      fullPath: '/jobs/'
      preLoaderRoute: typeof JobsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/google-feed/': {
      id: '/google-feed/'
      path: '/google-feed'
      fullPath: '/google-feed/'
      preLoaderRoute: typeof GoogleFeedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bulk-operations/': {
      id: '/bulk-operations/'
      path: '/bulk-operations'
      fullPath: '/bulk-operations/'
      preLoaderRoute: typeof BulkOperationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/prompts': {
      id: '/settings/prompts'
      path: '/settings/prompts'
      fullPath: '/settings/prompts'
      preLoaderRoute: typeof SettingsPromptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$productId': {
      id: '/products/$productId'
      path: '/products/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof ProductsProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$jobId': {
      id: '/jobs/$jobId'
      path: '/jobs/$jobId'
      fullPath: '/jobs/$jobId'
      preLoaderRoute: typeof JobsJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/google-feed/rules/': {
      id: '/google-feed/rules/'
      path: '/google-feed/rules'
      fullPath: '/google-feed/rules/'
      preLoaderRoute: typeof GoogleFeedRulesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/google-feed/preview/': {
      id: '/google-feed/preview/'
      path: '/google-feed/preview'
      fullPath: '/google-feed/preview/'
      preLoaderRoute: typeof GoogleFeedPreviewIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/google-feed/history/': {
      id: '/google-feed/history/'
      path: '/google-feed/history'
      fullPath: '/google-feed/history/'
      preLoaderRoute: typeof GoogleFeedHistoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  JobsJobIdRoute: JobsJobIdRoute,
  ProductsProductIdRoute: ProductsProductIdRoute,
  SettingsPromptsRoute: SettingsPromptsRoute,
  BulkOperationsIndexRoute: BulkOperationsIndexRoute,
  GoogleFeedIndexRoute: GoogleFeedIndexRoute,
  JobsIndexRoute: JobsIndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  GoogleFeedHistoryIndexRoute: GoogleFeedHistoryIndexRoute,
  GoogleFeedPreviewIndexRoute: GoogleFeedPreviewIndexRoute,
  GoogleFeedRulesIndexRoute: GoogleFeedRulesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
